issuer: http://10.104.223.225:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 0.0.0.0:5556

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    #host: blrqa-sam-lab.com:389
    host: WIN-CDGOM26LA5H.blrqa-sam-lab.com:389
    rootCA: /home/phireman/dex_backup/certnew.cer
    startTLS: true

    # No TLS for this setup.
    insecureNoSSL: false

    # This would normally be a read-only user.
    bindDN: CN=Administrator,CN=Users,DC=blrqa-sam-lab,DC=com
    bindPW: Nbv_12345

    usernamePrompt: Email Address

    userSearch:
      baseDN: DC=blrqa-sam-lab,DC=com
      filter: "(objectClass=person)"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: CN=Users,DC=blrqa-sam-lab,DC=com
      filter: "(objectClass=group)"

      # A user is a member of a group when their DN matches
      # the value of a "member" attribute on the group entity.
      userAttr: DN
      groupAttr: member

      # The group name should be the "cn" value.
      nameAttr: DN

      #Add also parents of group
      #inheritance: true
      recursive: true
      recursionGroupAttr: member

staticClients:
- id: intersight-onprem
  redirectURIs:
  - 'https://ucs.cisco.com:443/iam/oidc/oid/auth/callback'
  name: 'Intersight Onprem'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
